Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis 
Alt: real
Pes: real
IMC: real
Tep: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite sua altura")
leia(Alt)
Escreval("Digite seu peso")
leia(Pes)
Tep:=(Alt*Alt)
IMC:=(Pes/Tep)
Escreval("Seu IMC é ", IMC:6:2)

Fimalgoritmo